name: real_me_trotro
description: REAL ME TROTRO - GOV EDITION v11
publish_to: 'none'
version: 11.0.0+11
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.3
  shared_preferences: ^2.2.2
flutter:
  uses-material-design: true
