name: trotro_ticket
description: REAL ME TROTRO - QR ticket app for Trotro busses with fraud lock - Government Approved
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.7
  shared_preferences: ^2.2.2
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
