import 'dart:convert';import 'dart:math';import 'package:flutter/material.dart';import 'package:shared_preferences/shared_preferences.dart';import 'package:qr_flutter/qr_flutter.dart';import 'package:mobile_scanner/mobile_scanner.dart';import 'package:crypto/crypto.dart';
void main()=>runApp(const TrotroApp());
class TrotroApp extends StatelessWidget{const TrotroApp({super.key});@override Widget build(BuildContext c){return MaterialApp(debugShowCheckedModeBanner:false,home:const Home());}}
class Home extends StatefulWidget{const Home({super.key});@override State<Home> createState()=>_HomeState();}
class _HomeState extends State<Home>{
Map<String,Map<String,double>> routes={"cape coast":{"swedru":45,"accra":35,"kumasi":25},"swedru":{"cape coast":45,"accra":20,"kumasi":30},"accra":{"cape coast":35,"swedru":20,"kumasi":45},"kumasi":{"cape coast":25,"swedru":30,"accra":45,"tamale":65},"tamale":{"kumasi":65}};
Map<String,Map<String,String>> users={"admin":{"password":"Ad1My","station":"Head Office","role":"admin","full_name":"System Admin"}};
List<String> used=[];List<Map<String,dynamic>> sales=[];String curU="Guest",curR="passenger",curS="Head Office";
@override void initState(){super.initState();_load();}
Future<void> _load()async{final p=await SharedPreferences.getInstance();setState((){
routes=Map<String,Map<String,double>>.from(jsonDecode(p.getString('f')??jsonEncode(routes)).map((k,v)=>MapEntry(k as String,Map<String,double>.from((v as Map).map((kk,vv)=>MapEntry(kk as String,(vv as num).toDouble())))));
users=Map<String,Map<String,String>>.from(jsonDecode(p.getString('u')??jsonEncode(users)).map((k,v)=>MapEntry(k as String,Map<String,String>.from(v))));
used=List<String>.from(jsonDecode(p.getString('s')??"[]"));sales=List<Map<String,dynamic>>.from(jsonDecode(p.getString('sa')??"[]"));
curU=p.getString('cu')??"Guest";curR=p.getString('cr')??"passenger";curS=p.getString('cs')??"Head Office";});}
Future<void> _save()async{final p=await SharedPreferences.getInstance();await p.setString('f',jsonEncode(routes));await p.setString('u',jsonEncode(users));await p.setString('s',jsonEncode(used));await p.setString('sa',jsonEncode(sales));await p.setString('cu',curU);await p.setString('cr',curR);await p.setString('cs',curS);}
String suggest(String i){var u=i.toLowerCase().trim();if(routes.containsKey(u))return u;for(var k in routes.keys){if(k.contains(u)||u.contains(k.replaceAll(" ","")))return k;}return u;}
List<String> avail(){return [for(int i=1;i<=30;i++) "A${i.toString().padLeft(2,'0')}"].where((e)=>!used.contains(e)).toList();}
void sell(String name,String from,String to,double fare,String seat){final n=DateTime.now();final tid="T${Random().nextInt(90000)+9999}";final d="${n.year}-${n.month.toString().padLeft(2,'0')}-${n.day.toString().padLeft(2,'0')}";final t="${n.hour}:${n.minute}:${n.second}";final sale={"ticket_id":tid,"date":d,"time":t,"name":name,"from":from,"to":to,"fare":fare,"seat":seat,"sold_by":curU};setState((){sales.insert(0,sale);used.add(seat);});_save();final qr="REALME|$tid|$seat|${from.toUpperCase()}-${to.toUpperCase()}|$fare|$d";showDialog(context:context,builder:(_)=>AlertDialog(title:Text("SOLD $tid"),content:Column(mainAxisSize:MainAxisSize.min,children:[QrImageView(data:qr,size:150),Text("Name:$name\n$from->$to\nSeat:$seat\nGHS $fare")]),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text("OK"))]));}
@override Widget build(BuildContext c){
final av=avail();
return Scaffold(appBar:AppBar(backgroundColor:Colors.black,title:Text('TROTRO GOV - $curU ($curR) @ $curS',style:const TextStyle(color:Colors.white,fontSize:12))),
body:ListView(padding:const EdgeInsets.all(10),children:[
Container(color:Colors.black,padding:const EdgeInsets.all(10),child:Text('Safe. Fast. Reliable. | Gov Approved | DB trotro.db | $curU',style:const TextStyle(color:Colors.green,fontSize:10))),
ListTile(title:const Text("1. Passenger CHECK FARE"),onTap:(){String f="",t="";showDialog(context:context,builder:(_)=>AlertDialog(title:const Text("Check Fare"),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(decoration:const InputDecoration(labelText:"From"),onChanged:(v)=>f=v),TextField(decoration:const InputDecoration(labelText:"To"),onChanged:(v)=>t=v)]),actions:[TextButton(onPressed:(){final fs=suggest(f);final ts=suggest(t);if(routes[fs]?[ts]!=null){Navigator.pop(context);ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text("${fs.toUpperCase()}->${ts.toUpperCase()} = GHS ${routes[fs]![ts]}")));}},child:const Text("CHECK"))]));}),
ListTile(title:const Text("2. Station Master Login (admin/Ad1My)"),onTap:(){String u="",p="";showDialog(context:context,builder:(_)=>AlertDialog(title:const Text("Login"),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(onChanged:(v)=>u=v.toLowerCase().trim(),decoration:const InputDecoration(labelText:"Username")),TextField(onChanged:(v)=>p=v,decoration:const InputDecoration(labelText:"Password"),obscureText:true)]),actions:[TextButton(onPressed:(){if(users[u]?['password']==p){setState((){curU=u;curR=users[u]!['role']!;curS=users[u]!['station']!;});_save();Navigator.pop(context);} },child:const Text("LOGIN"))]));}),
ListTile(tileColor:Colors.orange[100],title:const Text("3. Create/Delete Account (Admin)"),onTap:(){if(curR!="admin"){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text("Admin only!")));return;}String nu="",np="",fn="",st="accra";showDialog(context:context,builder:(_)=>StatefulBuilder(builder:(ctx,setD)=>AlertDialog(title:const Text("Create Account"),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(decoration:const InputDecoration(labelText:"Username"),onChanged:(v)=>nu=v.toLowerCase()),TextField(decoration:const InputDecoration(labelText:"Full Name"),onChanged:(v)=>fn=v),TextField(decoration:const InputDecoration(labelText:"Password"),onChanged:(v)=>np=v),DropdownButton<String>(value:st,items:routes.keys.map((e)=>DropdownMenuItem(value:e,child:Text(e))).toList(),onChanged:(v)=>setD(()=>st=v!)),Text("Users: ${users.keys.join(', ')}",style:const TextStyle(fontSize:10))]),actions:[TextButton(onPressed:(){if(nu.isEmpty||users.containsKey(nu))return;setState(()=>users[nu]={"password":np,"station":st,"role":"station_master","full_name":fn});_save();Navigator.pop(context);},child:const Text("CREATE")),TextButton(onPressed:(){String du="";showDialog(context:context,builder:(_)=>AlertDialog(title:const Text("Delete"),content:TextField(onChanged:(v)=>du=v.toLowerCase(),decoration:const InputDecoration(labelText:"Username")),actions:[TextButton(onPressed:(){if(du!="admin"&&users.containsKey(du)){setState(()=>users.remove(du));_save();Navigator.pop(context);Navigator.pop(context);} },child:const Text("DELETE"))]));},child:const Text("DELETE",style:TextStyle(color:Colors.red))) ])));}),
ListTile(title:const Text("4. Verify Ticket"),onTap:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>VerifyPage(sales:sales)))),
if(curR!="passenger")...[
const Divider(),const Text("STATION MASTER MENU",style:TextStyle(fontWeight:FontWeight.bold)),
ListTile(tileColor:Colors.green[100],title:const Text(">>> SELL TICKET <<<"),subtitle:Text("Seats left ${av.length}/30: ${av.take(3).join(',')}"),onTap:(){String name="",from=curS=="Head Office"?"accra":curS,to="",seat=av.isNotEmpty?av[0]:"A01";showDialog(context:context,builder:(_)=>StatefulBuilder(builder:(ctx,setD)=>AlertDialog(title:const Text("Sell Ticket"),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(decoration:const InputDecoration(labelText:"Passenger Name"),onChanged:(v)=>name=v),TextField(decoration:InputDecoration(labelText:"From [$from]"),onChanged:(v)=>from=v.isEmpty?from:v),TextField(decoration:const InputDecoration(labelText:"To"),onChanged:(v)=>to=v),DropdownButton<String>(value:seat,items:av.map((e)=>DropdownMenuItem(value:e,child:Text(e))).toList(),onChanged:(v)=>setD(()=>seat=v!))]),actions:[TextButton(onPressed:(){final fs=suggest(from);final ts=suggest(to);if(routes[fs]?[ts]==null)return;Navigator.pop(context);sell(name,fs,ts,routes[fs]![ts]!,seat);},child:const Text("SELL"))])));}),
ListTile(title:const Text("View Routes / Update Fare"),onTap:(){showDialog(context:context,builder:(_)=>AlertDialog(title:const Text("Routes"),content:SizedBox(height:300,width:300,child:ListView(children:[for(var fs in routes.keys) for(var e in routes[fs]!.entries) Text("$fs -> ${e.key}: ${e.value}")])),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text("OK"))]));}),
ListTile(title:const Text("Seat Map"),onTap:(){showDialog(context:context,builder:(_)=>AlertDialog(title:const Text("Seat Map"),content:Wrap(spacing:5,children:[for(int i=1;i<=30;i++) Builder(builder:(_){final s="A${i.toString().padLeft(2,'0')}";return Container(padding:const EdgeInsets.all(6),color:used.contains(s)?Colors.red:Colors.green,child:Text(s,style:const TextStyle(color:Colors.white,fontSize:10)));})]),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text("OK"))]));}),
ListTile(title:const Text("Daily Sales Report"),onTap:(){final today=DateTime.now().toString().substring(0,10);final tod=sales.where((e)=>e['date']==today).toList();final money=tod.fold<double>(0,(a,b)=>a+(b['fare'] as num).toDouble());showDialog(context:context,builder:(_)=>AlertDialog(title:Text("Report $today"),content:Text("Today: ${tod.length} tickets\nGHS $money\nAll: ${sales.length}\nSeats left: ${30-used.length}/30"),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text("OK"))]));}),
ListTile(title:const Text("Export CSV"),onTap:(){final buf=StringBuffer("Ticket,Date,Name,From,To,Fare,Seat,SoldBy\n");for(var r in sales) buf.writeln("${r['ticket_id']},${r['date']},${r['name']},${r['from']},${r['to']},${r['fare']},${r['seat']},${r['sold_by']}");showDialog(context:context,builder:(_)=>AlertDialog(title:const Text("CSV Export"),content:SingleChildScrollView(child:Text(buf.toString(),style:const TextStyle(fontSize:8))),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text("OK"))]));}),
ListTile(tileColor:Colors.red[100],title:const Text("Reset Seats"),onTap:(){setState(()=>used=[]);_save();}),
ListTile(title:const Text("Logout"),onTap:(){setState((){curU="Guest";curR="passenger";curS="Head Office";});_save();}),
]
]));}}
class VerifyPage extends StatelessWidget{final List<Map<String,dynamic>> sales;const VerifyPage({super.key,required this.sales});@override Widget build(BuildContext c){return Scaffold(appBar:AppBar(title:const Text("Verify REALME|")),body:Column(children:[Expanded(child:MobileScanner(onDetect:(cap){final raw=cap.barcodes.first.rawValue??"";if(!raw.startsWith("REALME|"))return;final tid=raw.split("|")[1];final found=sales.where((e)=>e['ticket_id']==tid).toList();showDialog(context:c,builder:(_)=>AlertDialog(title:Text(found.isNotEmpty?"VALID":"FAKE"),content:Text(found.isNotEmpty?jsonEncode(found.first):"Fake $tid"),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text("OK"))]));})),Padding(padding:const EdgeInsets.all(10),child:TextField(decoration:const InputDecoration(labelText:"Paste REALME|..."),onSubmitted:(raw){if(!raw.startsWith("REALME|"))return;final tid=raw.split("|")[1];final found=sales.where((e)=>e['ticket_id']==tid).toList();showDialog(context:c,builder:(_)=>AlertDialog(title:Text(found.isNotEmpty?"VALID":"FAKE"),content:Text(found.isNotEmpty?jsonEncode(found.first):"Fake"),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text("OK"))]));}))]));}}
